name: itelligence_menu
description: A starting point for Dart libraries or applications.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  dio: ^3.0.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
