name: itelligence_menu
description: Scraper for the itelligence menu page
version: 0.2.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  html: ^0.14.0+3
  dio: ^3.0.9
  intl: ^0.16.1

dev_dependencies:
  mockito: ^4.1.1
  effective_dart: ^1.2.3
  test: ^1.15.0
  test_coverage: ^0.4.1
